-- Script para adicionar as colunas necessárias na tabela Motos
-- Execute este script no Oracle SQL Developer ou similar

-- Adicionar colunas na tabela Motos
ALTER TABLE "Motos" ADD "Latitude" NUMBER(10,8);
ALTER TABLE "Motos" ADD "Longitude" NUMBER(11,8);
ALTER TABLE "Motos" ADD "Endereco" NVARCHAR2(200);
ALTER TABLE "Motos" ADD "UltimaAtualizacao" TIMESTAMP(7);

-- Criar tabela Telemetria
CREATE TABLE "Telemetria" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "DeviceId" NUMBER(10) NOT NULL,
    "Timestamp" TIMESTAMP(7) NOT NULL,
    "Latitude" NUMBER(10,8) NOT NULL,
    "Longitude" NUMBER(11,8) NOT NULL,
    "Status" NVARCHAR2(50) NOT NULL,
    "Temperatura" NUMBER(5,2),
    "Velocidade" NUMBER(5,2),
    "Bateria" NUMBER(5,2),
    "Observacoes" NVARCHAR2(500),
    CONSTRAINT "PK_Telemetria" PRIMARY KEY ("Id")
);

-- Adicionar chave estrangeira
ALTER TABLE "Telemetria" ADD CONSTRAINT "FK_Telemetria_Motos_DeviceId" 
    FOREIGN KEY ("DeviceId") REFERENCES "Motos" ("IdMoto") ON DELETE CASCADE;

-- Inserir registros na tabela de migrations para marcar como aplicadas
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") 
VALUES ('20250509134329_InitialCreate', '8.0.0');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") 
VALUES ('20250509141124_UpdateMigration', '8.0.0');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") 
VALUES ('20250930181430_AddTelemetriaAndLocationFields', '8.0.0');

COMMIT;
