-- Script para criar apenas a tabela Telemetria
-- Execute este script no Oracle SQL Developer

-- Verificar se a tabela já existe e removê-la se necessário
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "Telemetria" CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- Criar tabela Telemetria
CREATE TABLE "Telemetria" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "DeviceId" NUMBER(10) NOT NULL,
    "Timestamp" TIMESTAMP(7) NOT NULL,
    "Latitude" NUMBER(10,8) NOT NULL,
    "Longitude" NUMBER(11,8) NOT NULL,
    "Status" NVARCHAR2(50) NOT NULL,
    "Temperatura" NUMBER(5,2),
    "Velocidade" NUMBER(5,2),
    "Bateria" NUMBER(5,2),
    "Observacoes" NVARCHAR2(500),
    CONSTRAINT "PK_Telemetria" PRIMARY KEY ("Id")
);

-- Adicionar chave estrangeira
ALTER TABLE "Telemetria" ADD CONSTRAINT "FK_Telemetria_Motos_DeviceId" 
    FOREIGN KEY ("DeviceId") REFERENCES "Motos" ("IdMoto") ON DELETE CASCADE;

-- Marcar a migration como aplicada
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") 
VALUES ('20250930193110_InitialCreate', '8.0.0');

COMMIT;
